### ISSUE TITLE
A cron job to check for new assemblies

### ISSUE THREAD

**Issue by leannehaggerty** [EnsemblGSOC/tony-gsoc-2018#15]
A cron job that runs every 24 hours (1am is a good time for it to run as the assembly registry updates at 12am), checks the registry for assemblies that have not been analysed, and sets the workflow running for any new assemblies.

Remember! The first time you run this ALL the assemblies will be new so it will trigger a lot of workflows... make sure you start with a test case that only runs the workflow for one assembly.

**Comment by tonyyzy** [comment]
Done.
Note for triggering large number of workflows, if the total number of workflow is greater than lsf job queue size (500?), toil.leader will saturate the jobs queue and prevent any actual jobs to run/finish. Hence the whole workflow will hang. Current solution is to try submit 200 workflows per hour. Furture, will implement a check for number of workflows currently running, and set the number to be lower than 500.

**Comment by tonyyzy** [comment]
Submit all the toil.leader to one host could also be a solution?
