### ISSUE TITLE
Is there a table for chromosomes under each GCA accession?

### ISSUE THREAD

**Issue by tonyyzy** [EnsemblGSOC/tony-gsoc-2018#17]
Hi @leannehaggerty 

I have taken a look at the assembly registry, all seem fairly intuitive. I wonder if there is a table contains all the chromosome accession numbers for each assembly?

If not, I have tried to pull the assembly info from ENA's record, parse the XML file and retrieve accessions for each chromosome. Then I will be able to construct a table myself from then on.

**Comment by leannehaggerty** [comment]
Hi Tony

The chromosome information is not stored in the assembly registry, we only use the registry to let us know when a new assembly has been added to NCBI, we then retrieve all extra information on an as-needed basis.
