### ISSUE TITLE
Flatfile format and track definition line

### ISSUE THREAD

**Issue by tonyyzy** [EnsemblGSOC/tony-gsoc-2018#7]
@andrewyatz 

I wondered around a bit more on ENA and I found the text format of a sequence which might be helpful. 
Such as this one:
[https://www.ebi.ac.uk/ena/data/view/A00145%26display%3Dtxt](https://www.ebi.ac.uk/ena/data/view/A00145%26display%3Dtxt)
Firstly, it contains the sequence length and more detailed descriptions about the nature of the sequence(contig etc.)
Secondly, it mentions a md5 checksum, the first DR line. Maybe a way to check the integrity of the downloaded fasta file is possible? I checked this md5 against the downloaded fasta file, as well as the text file itself, and it appears that this provided md5 doesn't match either. I then checked the newest manual [ftp://ftp.ebi.ac.uk/pub/databases/ena/sequence/release/doc/usrman.txt](ftp://ftp.ebi.ac.uk/pub/databases/ena/sequence/release/doc/usrman.txt)
and couldn't find any descriptions about this md5. Maybe you have some idea about what this md5 belongs to? If it takes a fair amount of your time to figure it out, I can contact helpdesk directly.

I remember you mentioned the xml file format will be removed? It would be nice to know if the flatfile format will be kept in the future.

In addition, I am trying to furnish my GC program's track definition line. Both UCSD and Ensembl's definition of a wiggle file mentioned "Chrom" as a required keyword. What about sequences that do not have a chromosome data? Such as mRNA? Does that mean wiggle file only apply to genome assemblies?

**Comment by andrewyatz** [comment]
Hi Tony.

Good hunting there. So this is the EMBL flat file record. It's the primary data format for records in EMBL. From my talks to the ENA guys there are no plans to remove this format at all. If you wanted to support it as an input to your program BioPython has bindings to parse this format https://biopython.org/wiki/SeqIO. Looks like you need to do

```python
from Bio import SeqIO
for record in SeqIO.parse("example.embl", "embl"):
    print(record.id)
```

The code there says it uses its genbank parser internally. This is fine the formats are pretty compatible with one and another. I would not recommend writing a parser by hand. There will be corner cases in a format that is deceptively simple. 

You're also right the MD5 relates to the sequence. It's the sequence with all spaces and numbers removed and then uppercased e.g.

```bash
$ echo -n 'ctgaaggaaggtcttcagagaacctagagagcaggttcacagagtcacccacctcaccaggccaaagcatctgcaaggtccccgatggccccagcctggtccttcctgctatccctgttgctgctcagctgcaacgccatctgctctctgggttgccacctgcctcacacccacagcctggccaacaggagggtcctgatgctcctgcaacaactgagaagggtctccccttcctcctgcctgcaggacagaaatgacttcgaattcctccaggaggctctgggtggcagccagttgcagaaggctcaagccatctctgtgctccacgaggtgacccagcacaccttccagctcttcagcacagagggctcgcccgccacgtgggacaagagcctcctggacaagctacgcgctgcgctggatcagcagctcactgacctgcaagcctgtctgacgcaggaggaggggctgcgaggggctcccctgctcaaggaggactccagcctggctgtgaggaaatacttccacagactcactctctatctgcaagagaagagacacagcccttgtgcctgggaggttgtcagagcagaagtcatgagagccttctcttcctcaacaaacttgcaggagagtttcaggagaaaggactgacacacacctggtccaacacggaaa' | tr '[a-z]' '[A-Z]' | md5
36b21ec05d6bd3bbaab87dd246820e87
```

The issue with using the flat files though is that when you look at chromosome records like this https://www.ebi.ac.uk/ena/data/view/CM000684&display=text (this is chromosome 22 in human) there's no sequence. Just a list of identifiers, which can be used to reassemble the sequence. Switching display to FASTA e.g. https://www.ebi.ac.uk/ena/data/view/CM000684&display=fasta will force it to create the full sequence.

Hope this helps

**Comment by andrewyatz** [comment]
Also yes GC is only used on genomic sequence. There's no value in calculating it against RNA. However your program should really only care about the ACTG and N nucleotides. If someone wants to put in a non-DNA sequence in then we probably should just let it ride and process it. Garbage in garbage out

**Comment by tonyyzy** [comment]
Thanks for the info. I am more thinking about downloading the flatfile along with the fasta file in a later stage (not relevant to the GC program) so I can check if the download was finished with no issue.

The reason why I care about if it's a genomic sequence is I want my GC program to extract the chromosome number and put it on the track definition line of the wiggle file. If it's an RNA sequence then there's no chromosome data then I should write an exception/warning for it. 

It's all sorted then, thanks!
